# Generated by Django 4.2.5 on 2024-05-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("umdb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("poster", models.ImageField(upload_to="posters/")),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                ("actors", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=100)),
                ("trailer_link", models.CharField(max_length=200)),
            ],
        ),
    ]
